name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        type: choice
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - uses: fregante/setup-git-user@v2

      - run: npm ci

      - run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build assets"

      - run: npm version ${{ github.event.inputs.type }}

      - run: git tag -a v$(jq -r '.version' package.json | awk -F. '{print $1}') -m ""

      - run: git push --follow-tags

      - run: gh release create v$(jq -r '.version' package.json)
        env:
          GH_TOKEN: ${{ github.token }}
